### ISSUE TITLE
Test full-width content on wider viewports 

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#182]

**Comment by andrewmarino** [comment]
full-bleed-text and full-bleed-image shortcodes both look good. I have a small fix for full-bleed-text.

@isabisa Should the full-bleed-image parallax? Wasn't sure since the classes / markup still exist but the JS is now gone.

**Comment by isabisa** [comment]
If there is a performant way to do make them parallax, then yes.

**Comment by andrewmarino** [comment]
Yep, I've had great results using Rellax in the past.

https://dixonandmoe.com/rellax/

**Comment by andrewmarino** [comment]
That Rellax is looking good! I removed the old parallax script used for hero images in the post header (if that's even relevant on the new site) https://github.com/unitymakesus/ednc-2020/commit/c87033ade9ef3e94fdc14c81039302414a7400a8. If we need to parallax those too, it's as easy as adding a class of `rellax` to the element.

https://edncstaging.wpengine.com/how-public-school-educators-built-a-radically-innovative-school/

And because we're handing it instead of a plugin, we can ignore initializing it if users prefer reduced motion for improved a11y.

**Comment by andrewmarino** [comment]
Looks like "tableaeu maps" (shortcode) are breaking out of their containers.

https://edncstaging.wpengine.com/exploring-statewide-trends-and-equity-gaps-in-north-carolina-districts-responses-to-covid-19/

**Comment by isabisa** [comment]
Looks good!
