### ISSUE TITLE
embed.php

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/ednc-2020#75]
This is only for oembeds of the articles. Need to be sure it's as stripped down as possible and doesn't have things like opt-in popups showing up _inside_ the oembed.

**Comment by isabisa** [comment]
Client also said there's "weird spacing on embedded WP articles"

**Comment by andrewmarino** [comment]
Hitting a wall with this one. Even the default iframe (by default it is hidden) is giving me this error in the console (not sure if it's because I'm testing this locally or what).

`Unsafe JavaScript attempt to initiate navigation for frame with URL 'https://ednc.test/embed-testing/' from frame with URL 'https://ednc.test/learning-differences-exceptional-children-covid19-challenges-remote-education/embed/#?secret=kP5rP8JoSM'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.`

**Comment by andrewmarino** [comment]
This is working a lot better, nice work!
